
export const ISLANDS = [
  { value: "mahe", label: "Mahe island" },
  { value: "praslin", label: "Praslin island" },
  { value: "ladigue", label: "La Digue island" },
  { value: "other", label: "Other" },
];

export const PROPERTIES = {
  mahe: [
    "Anse Soleil Beachcomber (Baie Lazare, Baie Lazare, Mahe Island)",
    "Au Fond De Mer View (Anse Royale, Anse Royale, Mahe Island)",
    "B Holiday Apartments (Belombre Road, Beau Vallon, Mahe Island)",
    "Canopy by HILTON (Anse La Mouche, Anse Boileau, Mahe Island)",
    "Crown Beach Hotel (East Coast Road, Pointe Au Sel, Au Cap, Mahe Island)",
    "Double Tree Allamanda by HILTON (Anse Forbans, South Coast Road, Takamaka, Mahe Island)",
    "East Horizon Self Catering (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "Four Seasons Resort Seychelles at Desroches Island (P.O. Box 755, Desroches Island, Seychelles)",
    "Georgina's Cottage Beach House (Mare Anglaise, Beau Vallon, Mahe Island)",
    "Green Palm Self Catering (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "Hibiscus House Seychelles Self Catering (Ma Constance Road, De Quincy, Anse Etoile, Mahe Island)",
    "Ksa Grann Kaz (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "La Desirade (Pointe Au Sel, Au Cap, Mahe Island)",
    "La Villa Therese Holiday Apartments (Anse Royale, Anse Royale, Mahe Island)",
    "Le Chateau Bleu (Reef Estate, Anse Aux Pins, Mahe Island)",
    "Le Jean Ville (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "Le Manglier Guest House (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "Le Noli (Anse Royale, Anse Royale, Mahe Island)",
    "Le Relax Beach House (Anse Royale, Anse Royale, Mahe Island)",
    "Le Relax Hotel And Restaurant (Pointe Au Sel, Au Cap, Mahe Island)",
    "Le Ronce Villa (Sweet Escott Road, Anse Royale, Anse Royale, Mahe Island)",
    "Maison Michel (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "Mer Riviere Self Catering (La Batie, Mare Anglaise, Beau Vallon, Mahe Island)",
    "Mouggae Blues (North Coast Road, Beau Vallon, Mahe Island)",
    "My Desroches Island (Desroches Island, Desroches Island)",
    "Paradise Chalets Yoga & Wellness (Anse Parnel, Takamaka, Mahe Island)",
    "Reef Villa (Anse Aux Pins, Anse Aux Pins, Mahe Island)",
    "Sun Properties & Resort (Beau Vallon, Beau Vallon, Mahe Island)",
    "Takamaka Green Village (Anse Takamaka, Takamaka, Mahe Island)",
    "Tamas Holiday Apartments (Beau Vallon, Beau Vallon, Mahe Island)",
    "The Palm Seychelles (The Palm Seychelles, Bel Ombre, Mahe Island)",
    "Zeph Self Catering Apartment (Anse Poules Bleues, Baie Lazare, Mahe Island)",
    "Hilton Seychelles Labriz Resort & Spa (Silhouette Island, Seychelles)",
  ],
  praslin: [
    "Acajou Beach Resort (Anse Volbert Village, Cote Dor, Baie Sainte-Anne, Praslin Island)",
    "Amity Villa (Cote D'or, Baie Ste Anne, Praslin Island)",
    "Berjaya Praslin Resort (Cote D'Or Esplanade, Baie St Anne, Praslin Island)",
    "Britannia Hotel (Grand Anse, Grand Anse, Praslin Island)",
    "Chauve Souris Relais (Cote D'or, Anse Volbert , Baie Ste Anne, Praslin Island)",
    "Fond B'offay Lodge (Baie-Ste Anne, Baie-Ste Anne, Praslin Island)",
    "Hotel Villas de Mer (Grand Anse Beach, Amitie, Praslin Island)",
    "Le Duc De Praslin (Anse Volbert, Cote D'or, Baie Ste Anne, Praslin Island)",
    "Le Vasseur La Buse Eco Resort (Anse Takamaka, Cot Dor, Praslin Island)",
    "L'Hirondelle (Cote D'Or , Baie Ste Anne, Praslin Island)",
    "Raffles Seychelles (Anse Boudin, Baie Ste Anne, Praslin Island)",
    "Sea View Lodge Self Catering Villas (Anse Possession, Baie Sainte Anne, Praslin Island)",
    "Paradise Sun Hotel (Cote D'Or Anse Volbert Praslin Island, Seychelles)",
    "Tropic Villa Annex (Amitie, Grand Anse, Praslin Island)",
  ],
  ladigue: [
    "Chalets Bamboo Vert (Anse Reunion, Anse Reunion, La Digue Island)",
    "Chez Michelin Pension Residence (La Passe, La Passe, La Digue Island)",
    "Hostellerie La Digue (La Passe, La Digue, La Passe, La Digue Island)",
    "La Digue Island Lodge (Anse Réunion La Digue, Seychelles, Seychelles)",
    "Mountain View Hotel (Grand Anse , Grand Anse, La Digue Island)",
    "Rising Sun Guesthouse (Anse Reunion, Anse Reunion, La Digue Island)",
  ],
};
